# Generated by Django 5.1.6 on 2026-01-20 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('region', models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], default='CA', max_length=2)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('on_hold', 'On hold'), ('in_production', 'In production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='processing', max_length=30)),
                ('rush_order', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('client_name', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tertiary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('quaternary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('order_name', models.CharField(max_length=255)),
                ('order_name_if_applicable', models.CharField(blank=True, max_length=255)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state_province', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('additional_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('client_pdf_url', models.URLField(blank=True)),
                ('admin_pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('processing', 'Processing'), ('on_hold', 'On hold'), ('in_production', 'In production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('new_status', models.CharField(choices=[('processing', 'Processing'), ('on_hold', 'On hold'), ('in_production', 'In production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['region', 'status'], name='orders_orde_region_909040_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['due_date'], name='orders_orde_due_dat_ac1ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rush_order'], name='orders_orde_rush_or_7983bc_idx'),
        ),
    ]
