# Generated by Django 5.1.6 on 2026-01-21 02:12

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_region_909040_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_due_dat_ac1ba1_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_rush_or_7983bc_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(choices=[('primary', 'Use Primary Location'), ('other', 'Other (specify)')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_pickup',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name_if_applicable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='rush_order',
            field=models.CharField(choices=[('standard', 'Standard'), ('rush', 'Rush')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to='order_files/%Y/%m/', validators=[orders.models.validate_file_extension, orders.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='size_bytes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
