# Generated by Django 5.1.6 on 2026-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_orders_orde_region_909040_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(choices=[('primary', 'Use Primary Location'), ('other', 'Other (specify)')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='rush_order',
            field=models.CharField(choices=[('standard', 'Standard'), ('rush', 'Rush')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
