# Generated by Django 5.1.6 on 2026-01-22 03:12

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_location_alter_order_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_pickup',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to=orders.models.order_file_upload_to, validators=[orders.models.validate_file_extension, orders.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
